-- ============================================================================
-- AI Trading Journal — Phase 3: AI coach report store.
--
-- One coaching report per user per day. Generated by the report cron (or the
-- on-demand route) from the user's computed analytics + behavioural signals +
-- goals + annotated trades, via Anthropic. Cached here so the dashboard reads
-- it instantly and we never regenerate on page load.
--
-- RLS: users read their OWN reports. Writes come only from the service role
-- (cron worker + admin on-demand route), which bypasses RLS.
-- ============================================================================

create table if not exists public.journal_reports (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users(id) on delete cascade,
  report_date  date not null,
  status       text check (status in ('ahead','on_track','behind','at_risk')),
  summary      text not null,
  habits       jsonb not null default '[]'::jsonb,
  tips         jsonb not null default '[]'::jsonb,
  stats        jsonb,
  model        text,
  created_at   timestamptz not null default now(),
  unique (user_id, report_date)
);

create index if not exists journal_reports_user_date_idx
  on public.journal_reports (user_id, report_date desc);

alter table public.journal_reports enable row level security;

create policy "journal_reports_select_own"
  on public.journal_reports for select
  to authenticated
  using (user_id = auth.uid());

-- ============================================================================
-- Scheduler — pg_cron + pg_net POST the report worker daily at 06:30 SGT
-- (22:30 UTC, after most sessions close). Same convention as journal-sync;
-- consumes no Vercel Hobby cron slot.
--
-- RUN ONCE IN THE SUPABASE SQL EDITOR (replace the two placeholders):
--
--   select cron.schedule(
--     'journal-report',
--     '30 22 * * *',
--     $$
--       select net.http_post(
--         url     := 'https://APP_URL/api/journal/cron/report',
--         headers := jsonb_build_object(
--           'Content-Type',  'application/json',
--           'Authorization', 'Bearer CRON_SECRET_VALUE'
--         ),
--         body    := '{}'::jsonb
--       );
--     $$
--   );
--
-- Verify:     select jobname, schedule, active from cron.job;
-- Unschedule: select cron.unschedule('journal-report');
-- ============================================================================
